--liquibase formatted sql

--changeset ignatov:001_create_users
CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(64)                           NOT NULL UNIQUE,
    password_hash VARCHAR(255)                          NOT NULL,
    role          VARCHAR(16)                           NOT NULL,
    created_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at    TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT chk_users_role CHECK (role IN ('USER','ADMIN'))
)

--changeset ignatov:002_create_cards
CREATE TABLE cards
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    encrypted_number VARCHAR(512)                          NOT NULL,
    number_hash      VARCHAR(64)                           NOT NULL UNIQUE,
    user_id          BIGINT                                NOT NULL,
    expiry           DATE                                  NOT NULL,
    balance          DECIMAL(19, 2)                        NOT NULL,
    status           VARCHAR(16)                           NOT NULL,
    created_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at       TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_card_owner FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_card_status
        CHECK (status IN ('CREATED', 'ACTIVE', 'BLOCK_REQUESTED', 'BLOCKED', 'EXPIRED')),

    CONSTRAINT chk_card_balance_nonneg CHECK (balance >= 0)
);

CREATE INDEX IF NOT EXISTS idx_card_user_id ON cards(user_id);
CREATE INDEX IF NOT EXISTS idx_card_number_hash ON cards(number_hash);

--changeset ignatov:003_create_transfer
CREATE TABLE transfer
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_card_id BIGINT                                NOT NULL,
    to_card_id   BIGINT                                NOT NULL,
    amount       DECIMAL(19, 2)                        NOT NULL,
    created_at   TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT fk_transfer_from FOREIGN KEY (from_card_id)
        REFERENCES cards (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_transfer_to FOREIGN KEY (to_card_id)
        REFERENCES cards (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_transfer_positive CHECK (amount > 0),
    CONSTRAINT chk_transfer_diff_cards CHECK (from_card_id <> to_card_id)
);

CREATE INDEX IF NOT EXISTS idx_transfer_from_card ON transfer(from_card_id);
CREATE INDEX IF NOT EXISTS idx_transfer_to_card ON transfer(to_card_id);

